# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiv12.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dagapy(object):
    def setupUi(self, dagapy):
        dagapy.setObjectName("dagapy")
        dagapy.resize(800, 430)
        font = QtGui.QFont()
        font.setPointSize(10)
        dagapy.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dagapy.setWindowIcon(icon)
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.line_3 = QtWidgets.QFrame(self.main)
        self.line_3.setGeometry(QtCore.QRect(10, 120, 431, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_27 = QtWidgets.QLabel(self.main)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 101, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.start_read = QtWidgets.QPushButton(self.main)
        self.start_read.setGeometry(QtCore.QRect(150, 70, 180, 50))
        self.start_read.setMinimumSize(QtCore.QSize(180, 50))
        self.start_read.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.start_read.setFont(font)
        self.start_read.setObjectName("start_read")
        self.label_44 = QtWidgets.QLabel(self.main)
        self.label_44.setGeometry(QtCore.QRect(10, 10, 271, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_54 = QtWidgets.QLabel(self.main)
        self.label_54.setGeometry(QtCore.QRect(10, 140, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.file_write = QtWidgets.QLabel(self.main)
        self.file_write.setGeometry(QtCore.QRect(120, 40, 301, 25))
        self.file_write.setMinimumSize(QtCore.QSize(0, 25))
        self.file_write.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_write.setFont(font)
        self.file_write.setFrameShape(QtWidgets.QFrame.Box)
        self.file_write.setText("")
        self.file_write.setObjectName("file_write")
        self.line_7 = QtWidgets.QFrame(self.main)
        self.line_7.setGeometry(QtCore.QRect(420, 0, 61, 391))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.read_file = QtWidgets.QPushButton(self.main)
        self.read_file.setGeometry(QtCore.QRect(135, 360, 180, 40))
        self.read_file.setMinimumSize(QtCore.QSize(150, 40))
        self.read_file.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.read_file.setFont(font)
        self.read_file.setObjectName("read_file")
        self.layoutWidget = QtWidgets.QWidget(self.main)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 235, 421, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.longi = QtWidgets.QComboBox(self.layoutWidget)
        self.longi.setObjectName("longi")
        self.gridLayout.addWidget(self.longi, 2, 1, 2, 1)
        self.atribute = QtWidgets.QComboBox(self.layoutWidget)
        self.atribute.setObjectName("atribute")
        self.gridLayout.addWidget(self.atribute, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 1, 0, 1, 1)
        self.lat = QtWidgets.QComboBox(self.layoutWidget)
        self.lat.setObjectName("lat")
        self.gridLayout.addWidget(self.lat, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 4, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 2, 0, 2, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 0, 0, 1, 1)
        self.delimiter = QtWidgets.QComboBox(self.layoutWidget)
        self.delimiter.setObjectName("delimiter")
        self.delimiter.addItem("")
        self.delimiter.addItem("")
        self.delimiter.addItem("")
        self.delimiter.setItemText(2, "")
        self.gridLayout.addWidget(self.delimiter, 0, 1, 1, 1)
        self.utm_check = QtWidgets.QCheckBox(self.main)
        self.utm_check.setGeometry(QtCore.QRect(20, 210, 136, 18))
        self.utm_check.setObjectName("utm_check")
        self.wdgt_main = mplwidget(self.main)
        self.wdgt_main.setGeometry(QtCore.QRect(470, 20, 306, 351))
        self.wdgt_main.setObjectName("wdgt_main")
        self.layoutWidget1 = QtWidgets.QWidget(self.main)
        self.layoutWidget1.setGeometry(QtCore.QRect(25, 165, 401, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.select_file = QtWidgets.QPushButton(self.layoutWidget1)
        self.select_file.setMinimumSize(QtCore.QSize(200, 30))
        self.select_file.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.select_file.setFont(font)
        self.select_file.setObjectName("select_file")
        self.horizontalLayout_3.addWidget(self.select_file)
        self.select_limit_file = QtWidgets.QPushButton(self.layoutWidget1)
        self.select_limit_file.setMinimumSize(QtCore.QSize(150, 30))
        self.select_limit_file.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.select_limit_file.setFont(font)
        self.select_limit_file.setObjectName("select_limit_file")
        self.horizontalLayout_3.addWidget(self.select_limit_file)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.line_3.raise_()
        self.label_27.raise_()
        self.start_read.raise_()
        self.label_44.raise_()
        self.label_54.raise_()
        self.file_write.raise_()
        self.line_7.raise_()
        self.read_file.raise_()
        self.utm_check.raise_()
        self.wdgt_main.raise_()
        dagapy.addTab(self.main, "")
        self.filter = QtWidgets.QWidget()
        self.filter.setObjectName("filter")
        self.fil_run = QtWidgets.QPushButton(self.filter)
        self.fil_run.setGeometry(QtCore.QRect(290, 350, 180, 50))
        self.fil_run.setMinimumSize(QtCore.QSize(180, 50))
        self.fil_run.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.fil_run.setFont(font)
        self.fil_run.setObjectName("fil_run")
        self.layoutWidget2 = QtWidgets.QWidget(self.filter)
        self.layoutWidget2.setGeometry(QtCore.QRect(15, 5, 766, 341))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wdgt_hist_before = mplwidget(self.layoutWidget2)
        self.wdgt_hist_before.setObjectName("wdgt_hist_before")
        self.horizontalLayout_2.addWidget(self.wdgt_hist_before)
        self.wdgt_hist_filter = mplwidget(self.layoutWidget2)
        self.wdgt_hist_filter.setObjectName("wdgt_hist_filter")
        self.horizontalLayout_2.addWidget(self.wdgt_hist_filter)
        dagapy.addTab(self.filter, "")
        self.kriging = QtWidgets.QWidget()
        self.kriging.setObjectName("kriging")
        self.splitter_14 = QtWidgets.QSplitter(self.kriging)
        self.splitter_14.setGeometry(QtCore.QRect(310, 10, 290, 0))
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName("splitter_14")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_14)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.line_5 = QtWidgets.QFrame(self.kriging)
        self.line_5.setGeometry(QtCore.QRect(250, 10, 46, 376))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.show_grid = QtWidgets.QPushButton(self.kriging)
        self.show_grid.setGeometry(QtCore.QRect(30, 165, 200, 60))
        self.show_grid.setMinimumSize(QtCore.QSize(200, 60))
        self.show_grid.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.show_grid.setFont(font)
        self.show_grid.setObjectName("show_grid")
        self.show_krig_error = QtWidgets.QPushButton(self.kriging)
        self.show_krig_error.setGeometry(QtCore.QRect(30, 305, 200, 60))
        self.show_krig_error.setMinimumSize(QtCore.QSize(200, 60))
        self.show_krig_error.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.show_krig_error.setFont(font)
        self.show_krig_error.setObjectName("show_krig_error")
        self.show_semiv = QtWidgets.QPushButton(self.kriging)
        self.show_semiv.setGeometry(QtCore.QRect(30, 95, 200, 60))
        self.show_semiv.setMinimumSize(QtCore.QSize(200, 60))
        self.show_semiv.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.show_semiv.setFont(font)
        self.show_semiv.setObjectName("show_semiv")
        self.show_krig_value = QtWidgets.QPushButton(self.kriging)
        self.show_krig_value.setGeometry(QtCore.QRect(30, 235, 200, 60))
        self.show_krig_value.setMinimumSize(QtCore.QSize(200, 60))
        self.show_krig_value.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.show_krig_value.setFont(font)
        self.show_krig_value.setObjectName("show_krig_value")
        self.krig_run = QtWidgets.QPushButton(self.kriging)
        self.krig_run.setGeometry(QtCore.QRect(30, 25, 200, 60))
        self.krig_run.setMinimumSize(QtCore.QSize(200, 60))
        self.krig_run.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.krig_run.setFont(font)
        self.krig_run.setObjectName("krig_run")
        self.wdgt_krig = mplwidget(self.kriging)
        self.wdgt_krig.setGeometry(QtCore.QRect(305, 20, 471, 366))
        self.wdgt_krig.setObjectName("wdgt_krig")
        self.splitter_14.raise_()
        self.line_5.raise_()
        self.show_krig_error.raise_()
        self.show_grid.raise_()
        self.show_semiv.raise_()
        self.show_krig_value.raise_()
        self.krig_run.raise_()
        self.wdgt_krig.raise_()
        dagapy.addTab(self.kriging, "")
        self.clustering = QtWidgets.QWidget()
        self.clustering.setObjectName("clustering")
        self.splitter_4 = QtWidgets.QSplitter(self.clustering)
        self.splitter_4.setGeometry(QtCore.QRect(20, 90, 16, 16))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.run_cluster = QtWidgets.QPushButton(self.clustering)
        self.run_cluster.setGeometry(QtCore.QRect(340, 335, 180, 60))
        self.run_cluster.setMinimumSize(QtCore.QSize(180, 60))
        self.run_cluster.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.run_cluster.setFont(font)
        self.run_cluster.setObjectName("run_cluster")
        self.wdgt_cluster = mplwidget(self.clustering)
        self.wdgt_cluster.setGeometry(QtCore.QRect(15, 5, 761, 316))
        self.wdgt_cluster.setObjectName("wdgt_cluster")
        dagapy.addTab(self.clustering, "")
        self.option = QtWidgets.QWidget()
        self.option.setObjectName("option")
        self.label_41 = QtWidgets.QLabel(self.option)
        self.label_41.setGeometry(QtCore.QRect(30, 10, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_48 = QtWidgets.QLabel(self.option)
        self.label_48.setGeometry(QtCore.QRect(350, 300, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setTextFormat(QtCore.Qt.AutoText)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.option)
        self.label_49.setGeometry(QtCore.QRect(440, 10, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.line = QtWidgets.QFrame(self.option)
        self.line.setGeometry(QtCore.QRect(0, 280, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.option)
        self.line_2.setGeometry(QtCore.QRect(390, 10, 41, 261))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.option)
        self.layoutWidget3.setGeometry(QtCore.QRect(31, 40, 351, 226))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)
        self.minVal = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.minVal.setMinimumSize(QtCore.QSize(80, 40))
        self.minVal.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.minVal.setFont(font)
        self.minVal.setDecimals(1)
        self.minVal.setMinimum(0.0)
        self.minVal.setMaximum(1000000000.0)
        self.minVal.setSingleStep(0.1)
        self.minVal.setProperty("value", 0.5)
        self.minVal.setObjectName("minVal")
        self.gridLayout_3.addWidget(self.minVal, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 0, 1, 1)
        self.maxVal = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.maxVal.setMinimumSize(QtCore.QSize(80, 40))
        self.maxVal.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maxVal.setFont(font)
        self.maxVal.setDecimals(1)
        self.maxVal.setMinimum(0.0)
        self.maxVal.setMaximum(1000000000.0)
        self.maxVal.setSingleStep(0.1)
        self.maxVal.setProperty("value", 8.0)
        self.maxVal.setObjectName("maxVal")
        self.gridLayout_3.addWidget(self.maxVal, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 2, 0, 1, 1)
        self.sd_ratio = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.sd_ratio.setMinimumSize(QtCore.QSize(80, 40))
        self.sd_ratio.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sd_ratio.setFont(font)
        self.sd_ratio.setDecimals(1)
        self.sd_ratio.setMinimum(0.5)
        self.sd_ratio.setMaximum(5.0)
        self.sd_ratio.setSingleStep(0.1)
        self.sd_ratio.setProperty("value", 2.5)
        self.sd_ratio.setObjectName("sd_ratio")
        self.gridLayout_3.addWidget(self.sd_ratio, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 3, 0, 1, 1)
        self.median_ratio = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.median_ratio.setMinimumSize(QtCore.QSize(80, 40))
        self.median_ratio.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.median_ratio.setFont(font)
        self.median_ratio.setDecimals(2)
        self.median_ratio.setMinimum(0.0)
        self.median_ratio.setMaximum(1.0)
        self.median_ratio.setSingleStep(0.05)
        self.median_ratio.setProperty("value", 0.25)
        self.median_ratio.setObjectName("median_ratio")
        self.gridLayout_3.addWidget(self.median_ratio, 3, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 4, 0, 1, 1)
        self.neig_dist = QtWidgets.QSpinBox(self.layoutWidget3)
        self.neig_dist.setMinimumSize(QtCore.QSize(80, 40))
        self.neig_dist.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.neig_dist.setFont(font)
        self.neig_dist.setMinimum(5)
        self.neig_dist.setMaximum(50)
        self.neig_dist.setProperty("value", 20)
        self.neig_dist.setObjectName("neig_dist")
        self.gridLayout_3.addWidget(self.neig_dist, 4, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.option)
        self.layoutWidget4.setGeometry(QtCore.QRect(440, 37, 311, 221))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 0, 0, 1, 1)
        self.max_dist = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.max_dist.setMinimumSize(QtCore.QSize(80, 40))
        self.max_dist.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.max_dist.setFont(font)
        self.max_dist.setDecimals(1)
        self.max_dist.setMinimum(0.1)
        self.max_dist.setMaximum(1.0)
        self.max_dist.setSingleStep(0.1)
        self.max_dist.setProperty("value", 0.6)
        self.max_dist.setObjectName("max_dist")
        self.gridLayout_4.addWidget(self.max_dist, 0, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 1, 0, 1, 1)
        self.lag = QtWidgets.QSpinBox(self.layoutWidget4)
        self.lag.setMinimumSize(QtCore.QSize(80, 40))
        self.lag.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lag.setFont(font)
        self.lag.setMinimum(5)
        self.lag.setMaximum(50)
        self.lag.setProperty("value", 15)
        self.lag.setObjectName("lag")
        self.gridLayout_4.addWidget(self.lag, 1, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_4.addWidget(self.label_52, 2, 0, 1, 1)
        self.neig = QtWidgets.QSpinBox(self.layoutWidget4)
        self.neig.setMinimumSize(QtCore.QSize(80, 40))
        self.neig.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.neig.setFont(font)
        self.neig.setMinimum(4)
        self.neig.setMaximum(50)
        self.neig.setProperty("value", 16)
        self.neig.setObjectName("neig")
        self.gridLayout_4.addWidget(self.neig, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 3, 0, 1, 1)
        self.gridsize = QtWidgets.QSpinBox(self.layoutWidget4)
        self.gridsize.setMinimumSize(QtCore.QSize(80, 40))
        self.gridsize.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.gridsize.setFont(font)
        self.gridsize.setMinimum(1)
        self.gridsize.setMaximum(100)
        self.gridsize.setProperty("value", 10)
        self.gridsize.setObjectName("gridsize")
        self.gridLayout_4.addWidget(self.gridsize, 3, 1, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.option)
        self.layoutWidget5.setGeometry(QtCore.QRect(4, 330, 246, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout.addWidget(self.label_53)
        self.n_clust = QtWidgets.QSpinBox(self.layoutWidget5)
        self.n_clust.setMinimumSize(QtCore.QSize(80, 40))
        self.n_clust.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.n_clust.setFont(font)
        self.n_clust.setMinimum(2)
        self.n_clust.setMaximum(5)
        self.n_clust.setProperty("value", 2)
        self.n_clust.setObjectName("n_clust")
        self.horizontalLayout.addWidget(self.n_clust)
        dagapy.addTab(self.option, "")

        self.retranslateUi(dagapy)
        dagapy.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dagapy)

    def retranslateUi(self, dagapy):
        _translate = QtCore.QCoreApplication.translate
        dagapy.setWindowTitle(_translate("dagapy", "DAGAPy"))
        self.label_27.setText(_translate("dagapy", "FILENAME:"))
        self.start_read.setText(_translate("dagapy", "START READ DATA"))
        self.label_44.setText(_translate("dagapy", "DATA ACQUISITION"))
        self.label_54.setText(_translate("dagapy", "DATA ANALYSIS"))
        self.read_file.setText(_translate("dagapy", "READ DATASET FILE"))
        self.label_30.setText(_translate("dagapy", "COORDINATE X:"))
        self.label_32.setText(_translate("dagapy", "ATRIBUTE (Z):"))
        self.label_31.setText(_translate("dagapy", "COORDINATE Y:"))
        self.label_33.setText(_translate("dagapy", "DELIMITER:"))
        self.delimiter.setItemText(0, _translate("dagapy", ","))
        self.delimiter.setItemText(1, _translate("dagapy", ";"))
        self.utm_check.setText(_translate("dagapy", "UTM Coordinate ?"))
        self.select_file.setText(_translate("dagapy", "SELECT DATASET FILE"))
        self.select_limit_file.setText(_translate("dagapy", "SELECT LIMIT FILE"))
        dagapy.setTabText(dagapy.indexOf(self.main), _translate("dagapy", "MAIN"))
        self.fil_run.setText(_translate("dagapy", "PROCESS FILTERING"))
        dagapy.setTabText(dagapy.indexOf(self.filter), _translate("dagapy", "FIlTERING"))
        self.show_grid.setText(_translate("dagapy", "SHOW GRID"))
        self.show_krig_error.setText(_translate("dagapy", "SHOW STD MAP"))
        self.show_semiv.setText(_translate("dagapy", "SHOW SEMIVARIOGRAM"))
        self.show_krig_value.setText(_translate("dagapy", "SHOW VARIABLE MAP"))
        self.krig_run.setText(_translate("dagapy", "PROCESS KRIGING"))
        dagapy.setTabText(dagapy.indexOf(self.kriging), _translate("dagapy", "KRIGING"))
        self.run_cluster.setText(_translate("dagapy", "PROCESS CLUSTERING "))
        dagapy.setTabText(dagapy.indexOf(self.clustering), _translate("dagapy", "CLUSTERING"))
        self.label_41.setText(_translate("dagapy", " FILTERING"))
        self.label_48.setText(_translate("dagapy", "CLUSTERING"))
        self.label_49.setText(_translate("dagapy", "KRIGING"))
        self.label_23.setText(_translate("dagapy", "LOWER THRESHOLD:"))
        self.label_24.setText(_translate("dagapy", "UPPER THRESHOLD:"))
        self.label_38.setText(_translate("dagapy", "SD FACTOR:"))
        self.label_39.setText(_translate("dagapy", "MEDIAN FACTOR:"))
        self.label_42.setText(_translate("dagapy", "NEIGHBOR DISTANCE (M):"))
        self.label_47.setText(_translate("dagapy", "LAG DIST. FACTOR:"))
        self.label_51.setText(_translate("dagapy", "# OF LAGS :"))
        self.label_52.setText(_translate("dagapy", "# OF NEIGHBOR:"))
        self.label_36.setText(_translate("dagapy", "GRID SIZE (M):"))
        self.label_53.setText(_translate("dagapy", "# OF CLASSES:"))
        dagapy.setTabText(dagapy.indexOf(self.option), _translate("dagapy", "CONFIGURATION PARAMETER"))
from mplwidget import mplwidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dagapy = QtWidgets.QTabWidget()
    ui = Ui_dagapy()
    ui.setupUi(dagapy)
    dagapy.show()
    sys.exit(app.exec_())
